version: 2
jobs:
  test:
    working-directory: ~/chat
    docker:
        - image: circleci/node:14.17.4 
          auth:
            username: fullhaider
            password: EFD4efz3BGmp28D # context / project UI env-var reference
    steps:
        - checkout
        - run: ls
        - name: Runs server tests
          working_directory: ./server
        - run: npm test

workflows:
  version: 2

  build_test:
    jobs:
      - test  
