version: 2.0
jobs:
  test:
    working_directory: ~\chat\server
    docker:
        - image: circleci/node:14.17.4
          auth:
            username: fullhaider
            password: EFD4efz3BGmp28D # context / project UI env-var reference
    steps:
        - checkout
        - run: ls
        - run: npm test
        - run: npm start

workflows:
  version: 2

  build_test:
    jobs:
      - test  

