versions: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node10
    steps:
      - checkout 
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run: 
          name: Run Unit tests
          command: npm test
