version: 2
jobs:
  test:
    working-directory: ~/chat/server
    docker:
        - image: circleci/node:14.17.4 
          auth:
            username: fullhaider
            password: EFD4efz3BGmp28D # context / project UI env-var reference
    steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
        - run: pwd
        - run: ls
        - run: npm run test

workflows:
  version: 2

  build_test:
    jobs:
      - test  
