version: 2
jobs:
  test:
    working_directory: ~/chat/server
    docker:
        - image: circleci/node:14.17.4 
          auth:
            username: fullhaider
            password: EFD4efz3BGmp28D # context / project UI env-var reference
    steps:
        - checkout
        - run: pwd
        - run: ls
        - run: jest

workflows:
  version: 2

  build_test:
    jobs:
      - test  
